### ISSUE TITLE
Component re-renders weird when params are added to url

### ISSUE THREAD

**Issue by yty-agnitio** [PDFTron/webviewer-react-sample#3]
Really not sure why this is happening when I add a route (with an extra slash) to the URL:

![image](https://user-images.githubusercontent.com/47319832/62702359-d6ddfd80-b9e6-11e9-8ac4-82c0f2e2a0da.png)

**Comment by vprsendic** [comment]
@yty-agnitio yes, do you have any console error? I'm getting _"Viewer is on a different domain, the promise from WebViewer function is rejected and API functions will not work because of cross domain permissions."_

**Comment by yty-agnitio** [comment]
@vprsendic, I get the same error but I don't really understand why. The Viewer is not on a different domain, it is locally located inside the **lib** folder. And the path is relative: `path: 'lib',`

**Comment by vprsendic** [comment]
@yty-agnitio same here, I spent 2 days trying to figure out and nothing :(

**Comment by mparizeau-pdftron** [comment]
@yty-agnitio The reason this is happening is because when you change the route like that then the `path` option in the WebViewer constructor is no longer correct since it's relative to the HTML location which now appears to be one directory down.

This means that the HTML page that WebViewer's iframe tries to load will not be found in the public folder since it's looking for `test/lib/ui/...` and create react app's default behavior is to load the index page when the file is missing which creates infinitely nested iframes...

One solution would be to change the `path` to be relative to the root. So you would just prefix it with a slash `path: '/lib'` inside App.js (similarly with the initialDoc path). We might change this sample to use these paths so that others won't run into this.

You may also want to use a router so you have more control over 404s https://facebook.github.io/create-react-app/docs/adding-a-router

@vprsendic It looks like this warning can happen if you pass an incorrect `path` to WebViewer because an error is thrown and the code currently assumes that an error will be thrown because it was unable to access the iframe and assumes it is on another domain.

The fix for both of these cases will be to fix the `path` so that it is correctly pointing to where WebViewer's lib folder is located.

**Comment by yty-agnitio** [comment]
Hi @mparizeau-pdftron,

`path: '/lib'` fixed the issue, but when I **build** the project, a similar problem is still present:

![image](https://user-images.githubusercontent.com/47319832/64113896-da696800-cd8b-11e9-89c2-a43b6eeade9d.png)

**Comment by mparizeau-pdftron** [comment]
Are you using `serve -s build` to run the build?

We made an update a couple weeks ago to add a configuration for serve as its default behavior was changing the URLs and breaking WebViewer. The commit was here https://github.com/PDFTron/webviewer-react-sample/commit/9427be16c22f0bec220e8ee991ffd50f116283b8 so I would try pulling the latest changes and trying again.

**Comment by edilsalvador** [comment]
Hi @mparizeau-pdftron, I tried the latest master branch and tried to run the webviewer using `serve -s build` and the problem with the nested iframe persists:
![image](https://user-images.githubusercontent.com/17653666/73044485-bcb8ae80-3ea4-11ea-96cc-a3a6a06f0154.png)

**Comment by mparizeau-pdftron** [comment]
Hmm, I just tried a clean run through of anything and it worked for me.
I cloned the repo, npm install, npm run build, serve -s build and the document loaded.

The issue happens because the lib/ui/index.html is 404ing and create-react-app redirects that to the home page. So you can check the network tab and see what path it's requesting for the UI and if that looks correct in your build folder.
