### ISSUE TITLE
Why do we need to explicitly copy the lib files in the public folder?

### ISSUE THREAD

**Issue by danantal** [PDFTron/webviewer-react-sample#8]
I was just curious, as long as we install `@pdftron/webviewer`, couldn't it automatically include the core files in the imports so that we don't need to serve the lib files separately and copy them manually to the public folder?

It feels a bit hacky.

**Comment by mparizeau-pdftron** [comment]
Thanks for the question! In theory this might be possible, but I'll first explain a bit about how it's working right now.

When you call the WebViewer constructor that is imported from `@pdftron/webviewer` it will create a new iframe element and set the src to be lib/ui/index.html. This HTML file contains script tags for lib/core/CoreControls.js (WebViewer core) and lib/ui/webviewer-ui.min.js (WebViewer UI). Depending on the browser and the type of document that you load, CoreControls will load other files dynamically (e.g. WebAssembly).

Having the HTML, JS and Wasm files available statically makes things simple as we just rely on normal browser requests to load the files. All we need to do it set the src of the iframe and everything will automatically work. We can also make normal JS requests for web workers and other dynamically loaded files.

If we wanted to make it so that you would just need to install `@pdftron/webviewer` the simple solution would just be to bundle every single file that might possibly be loaded into a massive JS file including non-JS content. Then at runtime we would extract the HTML data as a string to set the src of the iframe and maybe the JS as well. The extracted JS would then be run in the iframe and it would extract the Wasm to load dynamically. This bundle would be quite large so we'd probably want to split this up so we can lazy load only the modules we need.

To simplify things we'd probably want to get rid of the iframe as well. This comes with its own complications around conflicting CSS, resize events, etc. In theory this should all be possible but it will require more work on our side to investigate.

Note that WebViewer has been around for ~10 years, before npm was widely used in JavaScript projects which is part of the reason why it's structured as it is. We're working on improving the usage with npm and it's good to hear your feedback.

Let me know if you have any other questions!

**Comment by danantal** [comment]
Sorry for the late reply. It makes more sense now.

Indeed, it would be nice to think of ways to bring this into a friendlier npm environment, but I understand the complications it brings. I guess it's fine to close this.

Thanks for all the explanations.
